# Generated by Django 5.0.2 on 2024-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
