# Generated by Django 5.0.2 on 2024-02-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
