# Generated by Django 5.0.2 on 2024-02-19 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcategory",
            name="category_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="jobcontract",
            name="contract_type",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="career.jobcategory",
                to_field="category_name",
            ),
        ),
    ]
