# Generated by Django 5.0.2 on 2024-02-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_alter_joboffer_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="career.jobcategory",
                to_field="category_name",
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="contract_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="career.jobcontract",
                to_field="contract_type",
            ),
        ),
    ]
