# Generated by Django 5.0.2 on 2024-02-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0004_alter_joboffer_category_alter_joboffer_contract_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joboffer", old_name="Details", new_name="details",
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="contract_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="career.jobcontract"
            ),
        ),
    ]
