# Generated by Django 5.0.2 on 2024-02-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0005_rename_details_joboffer_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="career.jobcategory"
            ),
        ),
    ]
