# Generated by Django 5.0.2 on 2024-02-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0007_rename_details_joboffer_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joboffer", old_name="Details", new_name="details",
        ),
    ]
