# Generated by Django 5.0.2 on 2024-02-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0008_rename_details_joboffer_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="career.jobcategory",
                to_field="category_name",
            ),
        ),
    ]
